# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145CB9uKpOoy-_-kZ-_SxwTFfLoYgzpMq
"""

from google.colab import drive
drive.mount('/content/drive')
from torchvision import models
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")


model=models.resnet18(weights=None)
for params in model.parameters():
  params.requires_grad=False
model.fc=nn.Sequential(
    nn.Linear(512,512),
    nn.ReLU(),
    nn.Dropout(0,3),
    nn.Linear(512,2)
)
pro_path="/content/gender_classification_model.pth"

model.load_state_dict(torch.load(pro_path))
model=model.to(device)
model.eval()

transform=transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize([0.5,0.5,0.5],[0.5,0.5,0.5])
])
img_path="/content/img50.jpg"
img=Image.open(img_path).convert('RGB')
img=transform(img)
img=img.unsqueeze(0).to(device)

output=model(img)
_,predicted=torch.max(output.data,1)
if predicted.item()==0:
  print("Male")
else:
  print("Female")